name: Test HCLQ

on:
  push: 
    paths:
    - 'hclq/**'
    - .github/workflows/test-hclq.yml
jobs:
  test-hclq-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ./hclq
      with: 
        file_name: ./hclq/test/test.auto.tfvars
        transformation: set mytest goodvalue
    - name: verify contents
      run: |
        diff ./hclq/test/test.auto.tfvars hclq/test/test-expected.tfvars
